set_property IOSTANDARD LVCMOS33 [get_ports {A[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {A[0]}]
set_property PACKAGE_PIN V4 [get_ports {A[3]}]
set_property PACKAGE_PIN U4 [get_ports {A[2]}]
set_property PACKAGE_PIN U2 [get_ports {A[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {C[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {C[0]}]
set_property PACKAGE_PIN W7 [get_ports {C[6]}]
set_property PACKAGE_PIN W6 [get_ports {C[5]}]
set_property PACKAGE_PIN U8 [get_ports {C[4]}]
set_property PACKAGE_PIN V8 [get_ports {C[3]}]
set_property PACKAGE_PIN U5 [get_ports {C[2]}]
set_property PACKAGE_PIN V5 [get_ports {C[1]}]
set_property PACKAGE_PIN U7 [get_ports {C[0]}]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN U18 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

set_property PACKAGE_PIN W4 [get_ports {A[0]}]
